export interface LineSheetItem {
  id: number;
  name: string;
  balance: number;
  minOrderQuantity: number;
  sampleCost: number;
  productionCost: number;
  shipping: string;
  sampleLeadTime: string;
  bulkLeadTime: string;
  status: string;
  note: string;
  sizes: string;
  fabricMaterial: string;
  category: string;
  imageUrl: string;
}

export const lineSheetData: LineSheetItem[] = [
  {
    id: 1,
    name: "Xmas Ornament Cup",
    balance: 0,
    minOrderQuantity: 360,
    sampleCost: 300,
    productionCost: 3.5,
    shipping: "",
    sampleLeadTime: "2w 1d",
    bulkLeadTime: "",
    status: "Sample Designed",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/CupOrnamentMock.png?v=1727748702"
  },
  {
    id: 2,
    name: "Snow Globe",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 250,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "10-15 days",
    bulkLeadTime: "30-40 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Snowglobe.001.png?v=1727838391"
  },
  {
    id: 3,
    name: "Coveralls - quoting without printing",
    balance: 0,
    minOrderQuantity: 300,
    sampleCost: 100,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Sample Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/coverall.001.png?v=1727809605"
  },
  {
    id: 4,
    name: "Money counter",
    balance: 0,
    minOrderQuantity: 150,
    sampleCost: 150,
    productionCost: 87,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Sample Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Money_Counter.001.png?v=1727822101"
  },
  {
    id: 5,
    name: "House Slippers",
    balance: 0,
    minOrderQuantity: 500,
    sampleCost: 60,
    productionCost: 12.3,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Sample In Prodution",
    note: "House Slippers - 6 Sizes XS- XXL (35-45)",
    sizes: "XS-XXL (35-45)",
    fabricMaterial: "Embroidered top, Woven label inside, Inner fur is purple",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/House_Slippers.001.png?v=1727826310"
  },
  {
    id: 6,
    name: "Crystal Ashtrays  x5 colors      (100pc/ color)",
    balance: 0,
    minOrderQuantity: 500,
    sampleCost: 0,
    productionCost: 14.4,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Sample Made",
    note: "19*12.5*3cm box size ",
    sizes: "",
    fabricMaterial: "5 colors: Clear, Purple, Green, Red, Blue   ",
    category: "Home Goods",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/ALOCS_Ashtray.png?v=1727822111"
  },
  {
    id: 7,
    name: "Candles",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 250,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Home Goods",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/candle.pdf?v=1727838397"
  },
  {
    id: 8,
    name: "Sunglasses",
    balance: 0,
    minOrderQuantity: 100,
    sampleCost: 250,
    productionCost: 32,
    shipping: "",
    sampleLeadTime: "30-35 days",
    bulkLeadTime: "30-35 days",
    status: "Design Pending",
    note: "Waiting for glasses design have arms made",
    sizes: "N/a",
    fabricMaterial: "Metal, acetate",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/glasses.png?v=1727833591"
  },
  {
    id: 9,
    name: "Silicone lighter case",
    balance: 0,
    minOrderQuantity: 500,
    sampleCost: 150,
    productionCost: 2.6,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Samples Made",
    note: "Update ' design",
    sizes: "5 colors",
    fabricMaterial: "Silicone",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Lighter_Cases.001.png?v=1727830276"
  },
  {
    id: 10,
    name: "Tag pillow",
    balance: 0,
    minOrderQuantity: 100,
    sampleCost: 0,
    productionCost: 15,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Samples Made",
    note: "Updat vector design",
    sizes: "45x23cm",
    fabricMaterial: "Crystal plush",
    category: "Home Goods",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Tag_Pillow.001.png?v=1727830013"
  },
  {
    id: 11,
    name: "Fleece Blankets",
    balance: 0,
    minOrderQuantity: 500,
    sampleCost: 0,
    productionCost: 10,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Samples Made",
    note: "",
    sizes: "50x60 in",
    fabricMaterial: "Fleece ",
    category: "Home Goods",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/fleeceBlankets.001.png?v=1727822945"
  },
  {
    id: 12,
    name: "Ceramic Cookie Jar",
    balance: 0,
    minOrderQuantity: 500,
    sampleCost: 0,
    productionCost: 14.65,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-40 days",
    status: "Samples Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Home Goods",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/CookieJar.001.png?v=1727823409"
  },
  {
    id: 13,
    name: "Jaquard Towels",
    balance: 0,
    minOrderQuantity: 5500,
    sampleCost: 0,
    productionCost: 19,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-40 days",
    status: "Samples Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/towels.001.png?v=1727822384"
  },
  {
    id: 14,
    name: "Dominoes",
    balance: 0,
    minOrderQuantity: 150,
    sampleCost: 0,
    productionCost: 42,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-40 days",
    status: "Samples Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Dominoes.png?v=1727823416"
  },
  {
    id: 15,
    name: "Shoelaces",
    balance: 0,
    minOrderQuantity: 1500,
    sampleCost: 0,
    productionCost: 1.75,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "30-40 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/shoelace.png?v=1727833521"
  },
  {
    id: 16,
    name: "Jewelry Pendant",
    balance: 0,
    minOrderQuantity: 150,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/pendant.png?v=1727833644"
  },
  {
    id: 17,
    name: "Enamel Charm Bracelet",
    balance: 0,
    minOrderQuantity: 500,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/enamel.png?v=1727833715"
  },
  {
    id: 18,
    name: "Croc Jibbitz",
    balance: 0,
    minOrderQuantity: 1000,
    sampleCost: 0,
    productionCost: 0.8,
    shipping: "100",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/enamel.png?v=1727833715"
  },
  {
    id: 19,
    name: "Silicone Keychain",
    balance: 0,
    minOrderQuantity: 1000,
    sampleCost: 0,
    productionCost: 0.6,
    shipping: "100",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/enamel.png?v=1727833715"
  },
  {
    id: 20,
    name: "Enamel Pins",
    balance: 0,
    minOrderQuantity: 1000,
    sampleCost: 0,
    productionCost: 0.75,
    shipping: "250",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/enamel.png?v=1727833715"
  },
  {
    id: 21,
    name: "Socks",
    balance: 0,
    minOrderQuantity: 1000,
    sampleCost: 0,
    productionCost: 2.9,
    shipping: "1850",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Socks.001.png?v=1727824360"
  },
  {
    id: 22,
    name: "Scrunchies",
    balance: 0,
    minOrderQuantity: 1000,
    sampleCost: 0,
    productionCost: 2.85,
    shipping: "300",
    sampleLeadTime: "",
    bulkLeadTime: "15-20 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Scrunchie.001.png?v=1727836336"
  },
  {
    id: 23,
    name: "Basketball x2",
    balance: 0,
    minOrderQuantity: 150,
    sampleCost: 0,
    productionCost: 25,
    shipping: "550",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Basketball.001.png?v=1727826941"
  },
  {
    id: 24,
    name: "Duffle Bag",
    balance: 0,
    minOrderQuantity: 100,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Bags",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/duffle.001.png?v=1727834846"
  },
  {
    id: 25,
    name: "Snowboard",
    balance: 0,
    minOrderQuantity: 5,
    sampleCost: 1500,
    productionCost: 0,
    shipping: "300",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/snowboard.png?v=1727836157"
  },
  {
    id: 26,
    name: "Rolling Tray",
    balance: 0,
    minOrderQuantity: 1000,
    sampleCost: 0,
    productionCost: 2.5,
    shipping: "1200",
    sampleLeadTime: "",
    bulkLeadTime: "30-40 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/rollingtray.png?v=1727836706"
  },
  {
    id: 27,
    name: "Joint Roller",
    balance: 0,
    minOrderQuantity: 200,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/jointroller_jpg.webp?v=1727837985"
  },
  {
    id: 28,
    name: "Wave Cap",
    balance: 0,
    minOrderQuantity: 300,
    sampleCost: 80,
    productionCost: 2.5,
    shipping: "200",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Sample In Prodution",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Headwear",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/wavecap.png?v=1727836644"
  },
  {
    id: 29,
    name: "Bath Mats",
    balance: 0,
    minOrderQuantity: 150,
    sampleCost: 0,
    productionCost: 21.5,
    shipping: "1200",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Samples Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Home Goods",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Bath_Mats.001.png?v=1727829981"
  },
  {
    id: 30,
    name: "Shower Curtains",
    balance: 0,
    minOrderQuantity: 150,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Home Goods",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/curtain.png?v=1727837679"
  },
  {
    id: 31,
    name: "Pimple Patch",
    balance: 0,
    minOrderQuantity: 1000,
    sampleCost: 150,
    productionCost: 3.4,
    shipping: "",
    sampleLeadTime: "14-21 days",
    bulkLeadTime: "14-21 days",
    status: "Design Pending",
    note: "Case 40x40x12mm",
    sizes: "",
    fabricMaterial: "Plastic mirror case, Pimple patches, Mylar bag, Master case",
    category: "Skincare",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/ZitPAtches.001.png?v=1727848767"
  },
  {
    id: 32,
    name: "Shorts Bulk 3x design",
    balance: 0,
    minOrderQuantity: 750,
    sampleCost: 150,
    productionCost: 47,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Samples Made",
    note: "",
    sizes: "28, 30, 32, 34,36,38,40",
    fabricMaterial: "12oz light blue, washed blue, black  denim w/elastine, custom button, leather label",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Bulk_shorts.001.png?v=1727847987"
  },
  {
    id: 33,
    name: "Shorts Bulk Camo",
    balance: 0,
    minOrderQuantity: 250,
    sampleCost: 150,
    productionCost: 57,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "",
    note: "",
    sizes: "28, 30, 32, 34,36,38,40",
    fabricMaterial: "12oz camo w/elastine, custom button, leather label",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Bulk_Camo_Shorts.001.png?v=1727847971"
  },
  {
    id: 34,
    name: "Laser Jeans",
    balance: 0,
    minOrderQuantity: 150,
    sampleCost: 200,
    productionCost: 78,
    shipping: "",
    sampleLeadTime: "30-35 days",
    bulkLeadTime: "30-35 days",
    status: "Samples Made",
    note: "",
    sizes: "28, 30, 32, 34,36,38,40",
    fabricMaterial: " canvas, laser + screenprint, custom button, leather label, paint",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Laser_Jeans.001.png?v=1727828567"
  },
  {
    id: 35,
    name: "Mascot low",
    balance: 0,
    minOrderQuantity: 1,
    sampleCost: 0,
    productionCost: 1600,
    shipping: "350",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Branding",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/1mascot.jpg?v=1727837229"
  },
  {
    id: 36,
    name: "Mascot high",
    balance: 0,
    minOrderQuantity: 1,
    sampleCost: 0,
    productionCost: 3850,
    shipping: "350",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Branding",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Mascot.png?v=1727827862"
  },
  {
    id: 37,
    name: "Camo Shorts x3 design",
    balance: 0,
    minOrderQuantity: 600,
    sampleCost: 0,
    productionCost: 49,
    shipping: "6300",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Camo_shorts.001.png?v=1727828145"
  },
  {
    id: 38,
    name: "Open Weave Polo",
    balance: 0,
    minOrderQuantity: 200,
    sampleCost: 120,
    productionCost: 33,
    shipping: "1200",
    sampleLeadTime: "",
    bulkLeadTime: "30-35 days",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/openweave.png?v=1727838436"
  },
  {
    id: 39,
    name: "Halloween",
    balance: 0,
    minOrderQuantity: 560,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "In Production",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Halloween.001.png?v=1727829055"
  },
  {
    id: 40,
    name: "Mohair",
    balance: 54039,
    minOrderQuantity: 1720,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "14-21 Days",
    status: "Partial Production",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Mohair_.001.png?v=1727829632"
  },
  {
    id: 41,
    name: "Mens Underwear",
    balance: 0,
    minOrderQuantity: 350,
    sampleCost: 0,
    productionCost: 10.6,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Underwear.001.png?v=1727830933"
  },
  {
    id: 42,
    name: "Thong Underwear",
    balance: 0,
    minOrderQuantity: 350,
    sampleCost: 0,
    productionCost: 10.4,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Underwear.002.png?v=1727830934"
  },
  {
    id: 43,
    name: "Sports Bra",
    balance: 0,
    minOrderQuantity: 350,
    sampleCost: 0,
    productionCost: 10.6,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Underwear.003.png?v=1727830933"
  },
  {
    id: 44,
    name: "Wife beater",
    balance: 0,
    minOrderQuantity: 500,
    sampleCost: 0,
    productionCost: 12.25,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Sample Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/wife_beater.png?v=1727835104"
  },
  {
    id: 45,
    name: "Undershirt",
    balance: 0,
    minOrderQuantity: 500,
    sampleCost: 0,
    productionCost: 12.25,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Sample Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Undershirt.png?v=1727835243"
  },
  {
    id: 46,
    name: "Varsity",
    balance: 17942,
    minOrderQuantity: 900,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Bulk Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Varsity.001.png?v=1727834796"
  },
  {
    id: 47,
    name: "Umbrella",
    balance: 0,
    minOrderQuantity: 100,
    sampleCost: 0,
    productionCost: 23,
    shipping: "400",
    sampleLeadTime: "",
    bulkLeadTime: "15-20 days",
    status: "Sample Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/umbrella.001.png?v=1727825564"
  },
  {
    id: 48,
    name: "Puffer",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/alcs_puffer.001.png?v=1727836218"
  },
  {
    id: 49,
    name: "Coduroy Set",
    balance: 0,
    minOrderQuantity: 100,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Sample Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Corduroy_Set.001.png?v=1727824815"
  },
  {
    id: 50,
    name: "Cross body bag",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Bags",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/CrossBody.001.png?v=1727835629"
  },
  {
    id: 51,
    name: "Eye Drops",
    balance: 0,
    minOrderQuantity: 5000,
    sampleCost: 0,
    productionCost: 2.25,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/eyedrops.jpg?v=1727838552"
  },
  {
    id: 52,
    name: "Polo socks",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Polo_Socks.001.png?v=1727835780"
  },
  {
    id: 53,
    name: "Satin Starter jacket",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/satin.pdf?v=1727836284"
  },
  {
    id: 54,
    name: "Womens cropped varsity",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/crpopedvarsity.001.png?v=1727836360"
  },
  {
    id: 55,
    name: "Cashmere hearts cardigan",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/cashmere_Hearts_Cardigan.001.png?v=1727836054"
  },
  {
    id: 56,
    name: "Black Sashiko Denim",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Sample Made",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Black_Distressed.001.png?v=1727837187"
  },
  {
    id: 57,
    name: "Printed Rugs",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Print_Rugs.001.png?v=1727837962"
  },
  {
    id: 58,
    name: "Woven Rugs",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Design Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/woven_rugs.001.png?v=1727837971"
  },
  {
    id: 59,
    name: "Jaquard Blanket",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "New Deisgns Pending",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/IMG_7689.jpg?v=1727822530"
  },
  {
    id: 60,
    name: "Desto Work Jacket",
    balance: 0,
    minOrderQuantity: 100,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Thicker material",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Work_Set.001.png?v=1727826542"
  },
  {
    id: 61,
    name: "Desto Work Shirt",
    balance: 0,
    minOrderQuantity: 100,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Thicker material",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Work_Set.003.png?v=1727826551"
  },
  {
    id: 62,
    name: "Desto Work Pants",
    balance: 0,
    minOrderQuantity: 100,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "Rework",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Work_Set.004.png?v=1727826557"
  },
  {
    id: 63,
    name: "Hat press",
    balance: 0,
    minOrderQuantity: 1,
    sampleCost: 0,
    productionCost: 2800,
    shipping: "700",
    sampleLeadTime: "",
    bulkLeadTime: "20-30 Days",
    status: "New item",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "In store revenue generatot",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/hat_steamer.png?v=1727834515"
  },
  {
    id: 64,
    name: "Temp changing sweater",
    balance: 0,
    minOrderQuantity: 50,
    sampleCost: 120,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "Apparel",
    imageUrl: "https://cdn.shopify.com/s/files/1/0563/4464/1580/files/Color_Changing_Sweater.001.png?v=1727837525"
  },
  {
    id: 65,
    name: "Ski Goggles",
    balance: 0,
    minOrderQuantity: 0,
    sampleCost: 0,
    productionCost: 0,
    shipping: "",
    sampleLeadTime: "",
    bulkLeadTime: "",
    status: "",
    note: "",
    sizes: "",
    fabricMaterial: "",
    category: "",
    imageUrl: ""
  }
];